### ISSUE TITLE
Any ideas on these build errors?

### ISSUE THREAD

**Issue by arraybercov** [Cris21395/AzureKinectDK#1]
Heya, thanks for getting this going! Any ideas on these build errors? Have you gotten this working or is it just a start?

`Building 4 actions with 16 processes...
  [1/4] AzureKinectDKGameModeBase.cpp
  C:\Users\lagauche\Desktop\Cris21395\AzureKinectDK\Source\AzureKinectDK\AzureKinectDKGameModeBase.cpp(120): error C2065: 'K4ABT_JOINT_SPINE_NAVAL': undeclared identifier
  C:\Users\lagauche\Desktop\Cris21395\AzureKinectDK\Source\AzureKinectDK\AzureKinectDKGameModeBase.cpp(120): error C2660: 'AAzureKinectDKGameModeBase::DrawBone': function does not take 1 
arguments
  C:\Users\lagauche\Desktop\Cris21395\AzureKinectDK\Source\AzureKinectDK\AzureKinectDKGameModeBase.h(38): note: see declaration of 'AAzureKinectDKGameModeBase::DrawBone'
  C:\Users\lagauche\Desktop\Cris21395\AzureKinectDK\Source\AzureKinectDK\AzureKinectDKGameModeBase.cpp(121): error C2065: 'K4ABT_JOINT_SPINE_NAVAL': undeclared identifier
The terminal process terminated with exit code: 1`

**Comment by arraybercov** [comment]
Solved: K4ABT_JOINT_SPINE_NAVAL -> K4ABT_JOINT_SPINE_NAVEL

**Comment by Cris21395** [comment]
Hi @lagauche,
The project was developed for the 0.9.3 and 1.3.0 version. If you want to use the latest one you need to update the code taking into account the changes of that version, for example, the name of the joints.
