### ISSUE TITLE
Workaround to adding files into C:\Program Files\Epic Games\UE_4.24\Engine\Binaries\Win64

### ISSUE THREAD

**Issue by arraybercov** [Cris21395/AzureKinectDK#2]
Am I right that you found a workaround to adding anything to the Engine\Binaries folder? this seems to work without adding any .dlls or that dnn_model_2_0.onnx

**Comment by Cris21395** [comment]
Hi @lagauche,
Thanks for using my project. I didn't find a solution for what you say. My workaround was to add the `C:\Program Files\Azure Kinect Body Tracking SDK\tools` to the Environment variable's path and placing only the `dnn_model_2_0.onnx` and `cudnn64_7.dll` into the `Program Files/Epic Games/UE_4.23/Engine/Binaries/Win64`. It worked fine for me.
